services:
  - type: web
    name: entrack
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn entrack.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: entrack-db
          property: connectionString
      - key: SECRET_KEY
        value: "$zg_!oiik-f1t4h70#eku90501edf4a*9!qp8ckpc+k*r4k6yv"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "entrack.onrender.com"

databases:
  - name: entrack-db
    databaseName: entrack
    user: entrack
    plan: free
